version: "3.8"

services:
  web:
    build:
      context: .
    container_name: web
    ports:
      - "8000:8000"
    command: ["sh", "./start.sh"]
    env_file:
      - .env
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: