# Generated by Django 5.1.4 on 2024-12-09 12:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['slug'], name='article_art_slug_403059_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['author'], name='article_art_author__71ab43_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['created_date'], name='article_art_created_648f10_idx'),
        ),
    ]
